# Generated by Django 5.2.4 on 2025-10-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrestadorServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(db_index=True, max_length=100)),
                ('contato', models.CharField(db_index=True, max_length=50)),
                ('telefone', models.CharField(db_index=True, max_length=15)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': ('Prestador de Serviço',),
                'verbose_name_plural': 'Prestadores de Serviços',
                'ordering': ('empresa',),
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('prestador_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='servico.prestadorservico')),
            ],
            options={
                'ordering': ('nome',),
                'indexes': [models.Index(fields=['id', 'slug'], name='servico_ser_id_a75e5d_idx')],
            },
        ),
    ]
